language: node_js
node_js:
  - '6'
  - '4'

notifications:
  email:
    - valter.santos.matos@gmail.com

script:
  - npm run build  # build
  - npm run lint-ci  # lint
  - npm run coverage   # run mocha unit tests with coverage

after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
